name: Build and Upload Artifacts

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
#        os: ['ubuntu-latest', 'windows-latest']
        os: ['windows-latest']
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install Dependencies (Linux)
        run: sudo apt-get install ninja-build libboost-all-dev
        if: matrix.os == 'ubuntu-latest'
      - name: Install Dependencies (Windows)
        run: |
          choco install ninja
          ls C:/hostedtoolcache/windows/Boost/1.69.0/lib
        if: matrix.os == 'windows-latest'
      - name: Checkout Sources
        uses: actions/checkout@v1
      - name: Setup CMake
        run: |
          mkdir "${{ runner.workspace }}/build"
          cd "${{ runner.workspace }}/build"
          cmake $GITHUB_WORKSPACE -GNinja
        shell: bash
      - name: Build
        run: cmake --build .
        working-directory: ${{ runner.workspace }}/build
      - name: Upload Hexagon Library (Linux)
        uses: actions/upload-artifact@v1
        with:
          name: hexagon_library
          path: ${{ runner.workspace }}/build/hexlib/libhex_library.so
        if: matrix.os == 'ubuntu-latest'
      - name: Upload Hexagon Unsecure Library (Linux)
        uses: actions/upload-artifact@v1
        with:
          name: hexagon_unsecure_library
          path: ${{ runner.workspace }}/build/hexlib/libhex_unsecure_library.so
        if: matrix.os == 'ubuntu-latest'
      - name: Upload Hexagon Library (Windows)
        uses: actions/upload-artifact@v1
        with:
          name: hexagon_library
          path: ${{ runner.workspace }}/build/hexlib/Debug/hex_library.dll
        if: matrix.os == 'windows-latest'
      - name: Upload Hexagon Unsecure Library (Windows)
        uses: actions/upload-artifact@v1
        with:
          name: hexagon_unsecure_library
          path: ${{ runner.workspace }}/build/hexlib/hex_unsecure_library.dll
        if: matrix.os == 'windows-latest'

