name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - master

# Environment variables available to all jobs and steps in this workflow
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  RUN_REGION: us-west3
  SERVICE_NAME: hexcloud

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies (Linux)
        run: sudo apt-get install ninja-build libboost-all-dev
      - name: Checkout Sources
        uses: actions/checkout@v1
      - name: Setup CMake
        run: |
          mkdir "${{ runner.workspace }}/build"
          cd "${{ runner.workspace }}/build"
          cmake $GITHUB_WORKSPACE -GNinja
        shell: bash
      - name: Build
        run: cmake --build .
        working-directory: ${{ runner.workspace }}/build
      - name: Upload Hexagon Library
        uses: actions/upload-artifact@v1
        with:
          name: hexagon_library
          path: hexlib/libhex_library.so
      - name: Upload Unsecure Hexagon Library
        uses: actions/upload-artifact@v1
        with:
          name: hexagon_unsecure_library
          path: hexlib/libhex_unsecure_library.so

