name: Build and Upload Artifacts

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install Dependencies (Linux)
        run: sudo apt-get install ninja-build libboost-all-dev
        if: matrix.os == 'ubuntu-latest'
      - name: Install Dependencies (Windows)
        run: choco install ninja
        if: matrix.os == 'windows-latest'
      - name: Checkout Sources
        uses: actions/checkout@v1
      - name: Setup CMake
        run: |
          mkdir "${{ runner.workspace }}/build"
          cd "${{ runner.workspace }}/build"
          cmake $GITHUB_WORKSPACE -GNinja
        shell: bash
      - name: Build
        run: cmake --build .
        working-directory: ${{ runner.workspace }}/build
      - name: Upload Hexagon Library
        uses: actions/upload-artifact@v1
        with:
          name: hexagon_library
          path: ${{ runner.workspace }}/build/hexlib/libhex_library.so
      - name: Upload Hexagon Unsecure Library
        uses: actions/upload-artifact@v1
        with:
          name: hexagon_unsecure_library
          path: ${{ runner.workspace }}/build/hexlib/libhex_unsecure_library.so

